name: Correctness Checks
on: [push, pull_request]

permissions:
  contents: read

jobs:
  Run-Markdown-Checks:
    name: Run Markdown Checks
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@9c419aa98bfb42280bdae2b0a736befd9b01e3b1 # v4
        with:
          path: "tools/requirements.txt"
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"
      - name: Compute diff base
        id: base
        shell: bash
        run: |
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
                BASE="$(git merge-base \
                    "${{ github.event.pull_request.base.sha }}" \
                    "${{ github.event.pull_request.head.sha }}")"
            elif [[ "${{ github.event_name }}" == "push" ]]; then
                BASE="${{ github.event.before }}"
            else
                echo "Unsupported event: ${{ github.event_name }}" >&2
                exit 1
            fi

            echo "base=$BASE" >> "$GITHUB_OUTPUT"
      - name: inspect_links
        run: python3 tools/inspect_links.py --since "${{ steps.base.outputs.base }}"
      - name: inspect_markdown
        run: python3 tools/inspect_markdown.py --num-recent 5
